### ISSUE TITLE
Overwrites FMM even if version is >2.0.2

### ISSUE THREAD

**Issue by Clef-0** [ZeroGravityAntFarm/QOL-Updater#1]
QOL updater should check if the installed copy of FMM is equal or greater than the saved copy (this is stored in the assembly info).
![image](https://github.com/ZeroGravityAntFarm/QOL-Updater/assets/10343775/7bc34ec0-f5fe-4917-8eff-f1bf92d70d54)

Otherwise, someone who updates FMM to FMM3 (I'm working on this with an aim to release in a few weeks) before installing QOL patch will be downgraded back to 2.02.

**Comment by Sphyrna-029** [comment]
@Clef-0 do you have any ideas for checking FMM version programmatically? I found the byte address that stores the version in the binary but I don't know if this will be in the same place every release.

**Comment by Sphyrna-029** [comment]
> @Clef-0 do you have any ideas for checking FMM version programmatically? I found the byte address that stores the version in the binary but I don't know if this will be in the same place every release.

Looks like this is not the case :(

**Comment by Clef-0** [comment]
@Sphyrna-029 https://stackoverflow.com/questions/6470032/extract-assembly-version-from-dll-using-python Would the top answer on this work for you?

**Comment by Sphyrna-029** [comment]
Fixed in https://github.com/ZeroGravityAntFarm/QOL-Updater/commit/931fc81411cfedc26f30dd0adc0257ffcd0035c1
